apiVersion: v1
kind: Pod
metadata:
  name: ofed-driver
  labels:
    app: ofed-driver
spec:
  hostNetwork: true
  containers:
    - name: ofed-driver
      image: ofed_container
      imagePullPolicy: Never
      securityContext:
        privileged: true
      volumeMounts:
        - name: run-mofed
          mountPath: /run/mellanox/drivers
          mountPropagation: Bidirectional
        - name: etc-network
          mountPath: /etc/network
        - name: host-etc
          mountPath: /host/etc
        - name: host-udev
          mountPath: /host/lib/udev
  volumes:
    - name: run-mofed
      hostPath:
        path: /run/mellanox/drivers
    - name: etc-network
      hostPath:
        path: /etc/network
    - name: host-etc
      hostPath:
        path: /etc
    - name: host-udev
      hostPath:
        path: /lib/udev
